_description: &description
  en: |
    The application-model project.

project:
  subprojects:
  - group: 'laplacian-tutorial'
    type: 'application-model'
    name: 'application-model'
    namespace: 'laplacian.tutorial'
    description: *description
    version: '0.0.1'
#   source_repository:
#     url: https://github.com/laplacian-tutorial/application-model.git
    model_files:
    - dest/model
